# Generated by Django 4.2.7 on 2023-11-30 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, max_length=120, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.TextField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
